### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Maritzaspott** [AU-R-Data-Science/FinalProject_Group3#1]
- [ ] logistic regression @cek0060 
- [ ] confusion matrix @cek0060 
- [ ] bootstraps/ confidence intervals @Maritzaspott 
- [ ] vignettes @Maritzaspott 
- [ ] Plots @julietpetrisor
